### ISSUE TITLE
Proving Grounds Bot Crashes after 1st battle

### ISSUE THREAD

**Issue by kusyarudaora123** [Masuzu/ZooeyBot#1192]
If you select Proving Grounds , it will always bot crashes at the second party selection.
The same phenomenon seems to have happened at the time of the event. 　#1045
Is there a solution?

**Comment by CorrinKrow** [comment]
Having the same problem here, bot always crashes after 1st fight for extreme+

**Comment by ComfyEchooo** [comment]
Same issue here.

**Comment by Masuzu** [comment]
Please send a full report of the console messages + screenshot when this happens or the issue will be ignored.
The only error I had so far was an empty Result page error window popup.

**Comment by Hexalgene** [comment]
Mine just closes after the first battle. Couldn't catch any errors

**Comment by Masuzu** [comment]
Run ZooeyBot.exe from a command line window (powershell for instance, Shift + Right click on a folder)
![image](https://user-images.githubusercontent.com/5464705/58905378-83f37b80-8701-11e9-8fa2-6160729cbb20.png)

**Comment by Masuzu** [comment]
Some updates were published in v3.9.5 addressing the issues I personally had while farming the event.

**Comment by Hexalgene** [comment]
![image](https://user-images.githubusercontent.com/21688816/58905887-5f1cf980-873d-11e9-903a-53aa1f2950f0.png)
It stops here

**Comment by Masuzu** [comment]
What is your event mode section configuration?
My default selected parties for each battle match the configured party number for each stage, so that I never have to select a different party between stages. Maybe that's the issue?

**Comment by hebrew** [comment]
I also stop at the same place.
EventMode section is false.

It's just speculation ...
When selecting the first battle party, do not select the party specified by the cursor (the third party in this case).
So I think that there is a cause in the "selecting party" part.

```
[TreasureEventMode]
Enabled=true
# Url of the event page. The URL of the June 2017 dark GW is given as an example.
TreasureEventUrl=http://game.granbluefantasy.jp/#event/sequenceraid003/supporter/1400303
# Supported value are 'vh' (for "very hard"), 'ex' (for "extreme"), 'impossible' (introduced since the "Right Behind You" event), 'xeno-raid' (for the level 100 Xeno raid), 'gw' (for the preliminary round and first day of "Unite and Fight" nightmare mode level 90), 'gw-day-2-nm-90' for the second and 3rd days of "Unite and Fight" nightmare mode level 90, 'gw-day-2-nm-95' for the second and 3rd days of "Unite and Fight" nightmare mode level 95, 'gw-day-4-nm-90' for the 4th and last days of "Unite and Fight" nightmare mode level 90, 'gw-day-4-nm-95' for the 4th and last days of "Unite and Fight" nightmare mode level 95, 'gw-day-4-nm-100' for the 4th and last days of "Unite and Fight" nightmare mode level 100, proving-grounds (https://github.com/Masuzu/ZooeyBot/wiki/Treasure-Raid-Event-mode#proving-grounds)
Difficulty=proving-grounds
# Action point cost of the quest you are trying to start
ActionPointCost=40
TreasureEventModeScript=Scripts/pg_earth.lua


NightmareModeUrl=
NightmareModeScript=
# Comma-delimited list of summons which will be selected in priority if they are available for the nightmare mode.
# In case none of the preferred summons was found, select a random summon in the summon attribute tab defined by the parameter DefaultSummonAttributeTab, unless the parameter RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode is set to true.
NightmareModePreferredSummons=
# Zooey will reroll summons until one of the preferred summons for the nightmare mode is available, using trial battles to refresh the summon list.
RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode=true
# Set this parameter to true if the nightmare mode is available when you start Zooey so she can proceed to the nightmare stage right ahead.
NightmareModeAvailableAtStart=false

ProvingGroundsFirstBattlePreferredParty=3
ProvingGroundsSecondBattlePreferredParty=2
ProvingGroundsThirdBattlePreferredParty=1
```

![image](https://user-images.githubusercontent.com/35138410/58909892-284fdf00-874f-11e9-8e20-84733e8cc7ab.png)

**Comment by Masuzu** [comment]
That's really weird, I am now done automating through the whole the event and did not had that issue.
The next version will relax some settings.

**Comment by Hexalgene** [comment]
[TreasureEventMode]
Enabled=true
# Url of the event page. The URL of the June 2017 dark GW is given as an example.
TreasureEventUrl=http://game.granbluefantasy.jp/#event/sequenceraid003/supporter/1400303
# Supported value are 'vh' (for "very hard"), 'ex' (for "extreme"), 'impossible' (introduced since the "Right Behind You" event), 'xeno-raid' (for the level 100 Xeno raid), 'gw' (for the preliminary round and first day of "Unite and Fight" nightmare mode level 90), 'gw-day-2-nm-90' for the second and 3rd days of "Unite and Fight" nightmare mode level 90, 'gw-day-2-nm-95' for the second and 3rd days of "Unite and Fight" nightmare mode level 95, 'gw-day-4-nm-90' for the 4th and last days of "Unite and Fight" nightmare mode level 90, 'gw-day-4-nm-95' for the 4th and last days of "Unite and Fight" nightmare mode level 95, 'gw-day-4-nm-100' for the 4th and last days of "Unite and Fight" nightmare mode level 100, proving-grounds (https://github.com/Masuzu/ZooeyBot/wiki/Treasure-Raid-Event-mode#proving-grounds)
Difficulty=proving-grounds
# Action point cost of the quest you are trying to start
ActionPointCost=40
TreasureEventModeScript=Scripts/pgdirt.lua


NightmareModeUrl=
NightmareModeScript=
# Comma-delimited list of summons which will be selected in priority if they are available for the nightmare mode.
# In case none of the preferred summons was found, select a random summon in the summon attribute tab defined by the parameter DefaultSummonAttributeTab, unless the parameter RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode is set to true.
NightmareModePreferredSummons=Uriel
# Zooey will reroll summons until one of the preferred summons for the nightmare mode is available, using trial battles to refresh the summon list.
RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode=true
# Set this parameter to true if the nightmare mode is available when you start Zooey so she can proceed to the nightmare stage right ahead.
NightmareModeAvailableAtStart=false

ProvingGroundsFirstBattlePreferredParty=3
ProvingGroundsSecondBattlePreferredParty=2
ProvingGroundsThirdBattlePreferredParty=1

Tried the same setup as hebrew where first party is never selected. Same issue. After first battle zooey closes.

**Comment by Masuzu** [comment]
v3.9.6 added some workarounds.

> After first battle zooey closes.

Won't do anything about it: there is no way it can happen with the last build without throwing an error message.

**Comment by i-Grey** [comment]
Just let you know that I'm using 3.9.4 with EN version. 
It's running smoothly and flawless. I grind around 2 hours and I'm done.

**Comment by Hexalgene** [comment]
![image](https://user-images.githubusercontent.com/21688816/58914272-aa8cd300-8750-11e9-8e7b-30729f48599c.png)
Well it did just that with 3.9.6

**Comment by hebrew** [comment]
I also tried both JP / EN version at v 3.9.6, but stopped in the following cases.

・ Ignoring the party selection designation and entering a battle.
・ Stop at the second battle second party selection.
・ After repeating several times (all 10 battles or less).

**Comment by patrapornlee** [comment]
I got this problem as well and it reminds me of the problem with max time delay setting at the nearly top part of the ZooeyBot.ini file. I increased the number of time delay from 2700 to 5000 and it is fixed.

**Comment by JeremyMerkur** [comment]
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	ZooeyBot.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5cf6da18
  Fault Module Name:	ucrtbase.DLL
  Fault Module Version:	10.0.14393.2630
  Fault Module Timestamp:	5bbec6e6
  Exception Code:	40000015
  Exception Offset:	000891fa
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	456e
  Additional Information 2:	456ed71ab3c2999d3a218a3325691007
  Additional Information 3:	6447
  Additional Information 4:	6447bfb65d9365b1b7beb1c3318c7af8

**Comment by HrothgarOraen** [comment]
Definitely not an isolated thing.  Consistently crashing after first battle for me as well.

**Comment by CorrinKrow** [comment]
Bot still crashes after first battle with no error message in 3.9.6

**Comment by talran** [comment]
Just increases the max wait delays, having it too low will cause the bot to crash while attempting to determine the currently selected party.

I kicked everything up 2 seconds and it worked, dropping them back down again breaks it.
Might fiddle around later and see which one exactly it is.

`MaxPageLoadDelayInMsBeforeRetry=3500
# Maximum amount of time Zooey will wait for an expected event to occur (for instance, the attack button appearance) before triggering the fallback policy.
MaxTriggerDelayInMsBeforeFallback=6000
# Maximum delay before an action is deemed to have failed due to a lack of response from the GBF servers
MaxResponseDelayInMs=4000
# Maximum number of retry attempts when an action fails (due to a lack of response for instance) before the fallback policy kicks in
MaxNumActionRetries=2
MinWaitTimeInMsAfterRefresh=6000
# The bot will stop after the given parameter no matter what.
TimeLimitInSeconds=7000`

**Comment by JeremyMerkur** [comment]
Increasing the max delays doesn't help. I increased it by 5 seconds, still crashed. I increased it by an additional 90 seconds, still crashed (really fun waiting for more than a minute and a half for the "dismiss quest popup" step to time out).

**Comment by ComfyEchooo** [comment]
![2019-06-05_03-50-33](https://user-images.githubusercontent.com/37431438/58939416-300a8600-8745-11e9-83f4-ca271e0576b8.png)

Same issue. No changing the party configuration works here. Very strange. Tried increasing the delay, removing the lua script, nothing.

**Comment by patrapornlee** [comment]
I have run the program through debug mode, and capture the error. I hope this help.

>	[Frames below may be incorrect and/or missing, no symbols loaded for ucrtbase.dll]	Unknown
Unhandled exception at 0x774F1AEB (ucrtbase.dll) in ZooeyBot.exe: Fatal program exit requested. occurred

**Comment by Masuzu** [comment]
Hello,
I have some additional leads about what could cause this issue, the issue may actually not lie in the party selection but have to do with the raid result processing. Unfortunately I can't release any update for the next 5 or 6 hours.

**Comment by Masuzu** [comment]
v3.9.7 is up.

**Comment by Hexalgene** [comment]
Still closing after first battle sadly.

**Comment by Masuzu** [comment]
I think it's a ping issue. You guys probably have much better ping than I do for tests, making it guesswork.

**Comment by Masuzu** [comment]
Another iteration is up, with additional messages. Please do post those if you still face issues.

**Comment by kusyarudaora123** [comment]
It works properly when using version 3.9.8.
Thank you very much.

**Comment by HrothgarOraen** [comment]
3.9.8 is working for me as well.  Thank you for fixing this.

**Comment by hebrew** [comment]
Using v3.9.8 may work properly.
However, when stopping, it stops in the following situation.

```
New page loaded: http://game.granbluefantasy.jp/#result/553172178
Move to result page
Result page
Collecting proving grounds final reward
New page loaded: http://game.granbluefantasy.jp/#event/sequenceraid003/sequence_reward
New page loaded: http://game.granbluefantasy.jp/#event/sequenceraid003/supporter/1400303
Quest cost 40
Listing available summons
0.918367
Quest cost -1
Select summon ユグドラシル・マグナ (rank 2) in earth attribute tab at position 0
Selecting party
New page loaded: http://game.granbluefantasy.jp/#event/sequenceraid003/quest/1400303
Selecting party
ACDEYou current party is 1
ENew page loaded: http://game.granbluefantasy.jp/#quest/stage
New page loaded: http://game.granbluefantasy.jp/#quest/stage
ABNew page loaded: http://game.granbluefantasy.jp/#raid/553172421
BBParty selection will be skipped
EABBBParty selection will be skipped
Selecting party 1F
PS C:\userapp\GBF\zooey-bot-v3.9.8>
```

**Comment by Masuzu** [comment]
@hebrew I am afraid I do not see how you could have something like this:
```
Selecting party
ACDEYou current party is 1
ENew page loaded: http://game.granbluefantasy.jp/#quest/stage
New page loaded: http://game.granbluefantasy.jp/#quest/stage
ABNew page loaded: http://game.granbluefantasy.jp/#raid/553172421
BBParty selection will be skipped
EABBBParty selection will be skipped
Selecting party 1F
```
which in my eyes would amount from immediately moving to the raid without even clicking on the 'Start' button? What is exactly happening?

**Comment by hebrew** [comment]
@Masuzu 
ZooeyBot, click on the 'Start' button of the first battle to complete the summon selection.
After that, do nothing in the first battle raid and stop working.

**Comment by Masuzu** [comment]
Thank you, I understand the situation better now. That could indeed happen if you happen to click several times on a same summon after failing to select it a first time. Increasing the configuration parameter `MaxResponseDelayInMs` may help to avoid these situations in the meantime. I will release an additional fix for this later today.

**Comment by Masuzu** [comment]
Updates for the last issue aforementioned have been added in v3.9.9, happy farming!

**Comment by GranblueOjisan** [comment]
I had same problem in past pg(wind)
but I could not explain it because of my bad English
finally you fixed it! woot thank you!

**Comment by Hexalgene** [comment]
Working for me now. Thanks!

**Comment by Masuzu** [comment]
Good to hear!
